[build]
  publish = "convoy/"
  # command = ""

[functions]
  directory = "envoy/"
  node_bundler = "esbuild"

[[redirects]]
  from = "/cdn/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/shop/*"
  to = "/shop/index.html"
  status = 200

[[redirects]]
  from = "https://shop.trifect.show/*"
  to = "/shop/index.htm"
  status = 200
  force = true
  
[[redirects]]
  from = "https://trifect.show/mc"
  to = "https://www.dropbox.com/scl/fo/om95ypt98xsdr21doosj9/ADeNx8nREqnuFSV2IUdu4sk?rlkey=v7aj0ldytza2ah7umhe4eqoye&st=evjcgnmj&dl=1"
  status = 200
  force = true

[[headers]]
  for = "https://shop.trifect.show/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = """
      default-src 'self' https://trifect.myspreadshop.com;
      frame-src https://trifect.myspreadshop.com https://*.spreadshirt.com;
      script-src 'self' 'unsafe-inline' https://trifect.myspreadshop.com https://*.spreadshirt.com;
      style-src 'self' 'unsafe-inline' https://trifect.myspreadshop.com https://*.spreadshirt.com;
      img-src 'self' data: https://*.spreadshirt.com;
      connect-src 'self' https://trifect.myspreadshop.com https://*.spreadshirt.com;
    """